# Chapter 05
## Model Evaluation and Two Algorithm

## Evaluation 1

## Using one dataset for training and test is prohibited

### Lets try to use one dataset for training and test and experience what happens

In [23]:
import numpy as np
import pandas as pd

In [24]:
#loading iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

#defining feature and target
X = iris.data
y = iris.target

# using KNeighborsClassifer with neighbors 3

In [25]:
from sklearn.neighbors import KNeighborsClassifier

#intancetiate of the model
knn = KNeighborsClassifier(n_neighbors = 5)

#making the relation in model
knn.fit(X, y)

knn.predict(X) #predicting the model using the value given in x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
knn.predict(X) == y #matching with the actual label

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,

In [27]:
#check first 5 item
knn.predict(X)[0:5]

array([0, 0, 0, 0, 0])

In [28]:
y_predicted = knn.predict(X) #storing the value

len(y_predicted) #length of predicted item

150

## Now checking Accuracy using the score function

In [29]:
knn.score(X, y)

0.9666666666666667

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y, y_predicted) #comparing with the target and predicted data

0.9666666666666667

# as we use one dataset for training and test, we can say that it is training accuracy
## Thus, our training accuarcy is 96%

In [31]:
np.mean(y_predicted == y) #returns the mean of the boolean array, which already show you above, containing True and False

0.9666666666666667

In [32]:
#import confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_predicted)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]], dtype=int64)

# lets check with the n_neighbors 1

In [33]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X, y)
y_predicted = knn.predict(X)
accuracy_score(y, y_predicted)

1.0

## wow 100% accuracy score
### its not good, in this way it will be overfit model

# Confusion Matrix

|                     | Predicted Positive | Predicted Negative |
|---------------------|--------------------|--------------------|
| Actual Positive     | True Positive (TP) | False Negative (FN)|
| Actual Negative     | False Positive (FP)| True Negative (TN) |


In [34]:
#import confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_predicted)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]], dtype=int64)

# <center><font size="50" color="red">Thank You</font></center>